### PR TITLE
[i18n] Fix German Translation

### PR DESCRIPTION
**Pull request by moschlar**

### CODE REVIEW

**Comment by freeplant** [comment]
Hello, please fix the translation at the Transifex. Because the file here is an automatically generated one.

**Comment by moschlar** [comment]
I would, if I were able to join the team there! ;-)

**Comment by freeplant** [comment]
I have approved the join request. Please try again.

**Comment by moschlar** [comment]
Ok, then this typo was already fixed there three months ago. ;-)

**Pull request closed without merging**
