### PR TITLE
Corrected some of the English in seahub/templates/libraries.html

### PR DESCRIPTION
**Pull request by phillym**
Also corrected references in Django locale LC_Messages files.

Mostly changes very very minor (but significant for native English speakers), only rewrote two lines
seahub/templates/libraries.html lines 80 and 82

### CODE REVIEW

**Comment by xiez** [comment]
@phillym thanks! We'll review soon.

**Comment by xiez** [comment]
@phillym  could you please remove all the changes of .po files in locale directory, since we use Transifex to manage our po files.

**Comment by shoeper** [comment]
Almost all of these changes are in po files. Is there no option to import these changes back into transifex?

**Comment by phillym** [comment]
I'll revert all .po changes and resubmit

**Pull request closed without merging**
