### PR TITLE
Onlyoffice edit file extension

### PR DESCRIPTION
**Pull request by TMHBOFH**

### CODE REVIEW

**Comment by xiez** [comment]
Hi @TMHBOFH , any reason why we need editable extension here ?

**Comment by TMHBOFH** [comment]
Hi @xiez,
because [this](https://forum.seafile.com/t/onlyoffice-corrupts-odt/2793/29?u=tmhbofh) situation with open document files.
This [idea ](https://github.com/haiwen/seahub/pull/1617) I have rejected.
What think you about?

**Comment by shoeper** [comment]
> any reason why we need editable extension here ?

to allow opening microsoft files readonly to not break them and read and edit odf files at the same time.

**Comment by TMHBOFH** [comment]
@shoeper the problem are odt files not microsoft files

**Comment by shoeper** [comment]
Yeah, sorry. You're right, it's the other way around.

**Comment by xiez** [comment]
Okay cool! Thank you guys!

**Pull request merged**
