### PR TITLE
Update Build scripts

### PR DESCRIPTION
**Pull request by Gustl22**
As you moved the scripts from seafile-server to seahub, changes in the build scritpt are needed. See #5050 

Also adding go server, thx to @jobenvil :D

I wonder how you can build for your own? Is there an internal build script?

### CODE REVIEW

**Review by jobenvil — APPROVED** [review]

**Review by jobenvil — APPROVED** [review]

**Review by jobenvil — APPROVED** [review]

**Review by jobenvil — APPROVED** [review]

**Comment by Gustl22** [comment]
Thanks @ChatDeBlofeld 
I was confused because the scripts were deleted afterwards in 62bf7da4c8d380aadf733126a23cc91e624214af and I included they weren't needed anymore. But they are still present here: https://github.com/haiwen/seafile-server/tree/master/scripts/sql
I'll rewrite the section.

**Comment by Gustl22** [comment]
@freeplant can you have a look? 

Pytests failed, but they always were skipped in the other PRs.

**Comment by Gustl22** [comment]
@freeplant pytests succeed now, would you mind merging? Thx ;D

**Comment by Gustl22** [comment]
@freeplant any plans to support legacy build script?

**Pull request merged**
