### PR TITLE
Remove unreachable code

### PR DESCRIPTION
**Pull request by bougault**
```python
    if getattr(settings, 'ENABLE_OAUTH', False):
        return HttpResponseRedirect(reverse('oauth_login') + next_param)

    if getattr(settings, 'ENABLE_CAS', False):
        return HttpResponseRedirect(reverse('cas_ng_login') + next_param)

    if getattr(settings, 'ENABLE_OAUTH', False):
        return HttpResponseRedirect(reverse('oauth_login'))
```
The 'ENABLE_OAUTH block is duplicated, so the second one is dead code.

### CODE REVIEW

**Comment by shoeper** [comment]
Are you sure it is unreachable? It depends on the configuration.

**Comment by bougault** [comment]
```python
    if getattr(settings, 'ENABLE_OAUTH', False):
        return HttpResponseRedirect(reverse('oauth_login') + next_param)

    if getattr(settings, 'ENABLE_CAS', False):
        return HttpResponseRedirect(reverse('cas_ng_login') + next_param)

    if getattr(settings, 'ENABLE_OAUTH', False):
        return HttpResponseRedirect(reverse('oauth_login'))
```
Yes, in this snippet, third condition is the same as the first one so it can be reached

**Comment by shoeper** [comment]
Sorry, totally missed that.

**Comment by xiez** [comment]
Merged! Thanks guys!

**Pull request merged**
