### PR TITLE
updated slovenian translations

### PR DESCRIPTION
**Pull request by Pubec**
A lot of slovenian translation are wrong, misspelled or have their meaning uncorrect to their english counterpart.

### CODE REVIEW

**Comment by Michael18811380328** [comment]
Thank you for your support of our translation work.
You can visit https://app.transifex.com/haiwen/seahub/translate/#/sl_SI
We will regularly update the translation files into the Seahub project code to complete the Slovenian translation.

**Comment by Pubec** [comment]
> Thank you for your support of our translation work. You can visit https://app.transifex.com/haiwen/seahub/translate/#/sl_SI We will regularly update the translation files into the Seahub project code to complete the Slovenian translation.

Would love to contribute over transifex.com, but it is only possible to do so with an business email account. So this is my only option so far.

**Comment by Michael18811380328** [comment]
> but it is only possible to do so with an business email account.

You don't need to register a business email, you can log in to this website through a Google account or GitHub account and then translate.

截屏2024-11-23 09 32 04
截屏2024-11-23 09 33 32

**Comment by Pubec** [comment]
Screenshot_20241123_125607_Firefox

**Comment by Michael18811380328** [comment]
> Screenshot_20241123_125607_Firefox

To register for a free Transifex account, you can: 

1. Go to app.transifex.com/signup 
2. Fill out the form with your first and last name, the languages you speak, and create a username and password 
3. Activate your account 

You can also link an existing account from GitHub, Google, or LinkedIn to avoid creating a new password. 
To join a translation team, you can:
1. Search for a project on the Explore page(seahub)
2. Click on the project's name
3. Click the JOIN THIS PROJECT button
4. Select your language
5. Click Request Language or Join Project 

For more information and details, please visit https://opensource.creativecommons.org/contributing-code/translation-guide/

**Comment by Michael18811380328** [comment]
If you don't have a business email, you can log in to this website through a Google account or GitHub account. I can use Github account to log in the app.transifex.com. Here is the detail. Alternatively, you can try changing to another email address. If none of the above methods can log in, we will further handle this issue.

**Comment by Pubec** [comment]
I still have troubles joining Transifex. I can not joint the project, and I get a warning `... there are 13 days left in your <username> trial`.
Is there another way to contribute to translation? Maybe over git?

**Comment by Michael18811380328** [comment]
> I still have troubles joining Transifex. I can not joint the project, and I get a warning `... there are 13 days left in your <username> trial`. Is there another way to contribute to translation? Maybe over git?

We have changed the steps of join Transifex and added some details.

Please submit translations via Transifex:

Steps:

1. Visit the webpage of Transifex (https://explore.transifex.com/haiwen/seahub/).

2. Click the "Join this project" button in the bottom right corner.

3. Use an email or GitHub account(recommended) to create an account.

4. Select a language and click 'Join project' to join the language translation.

5. After accepted by the project maintainer, then you can upload your file or translate online.

**Comment by Michael18811380328** [comment]
> I have now successfully sent a join request on `transifex`.

Our team have received your join request and now you can translate on Transifex. 

We will regularly download translation files from Transifex then update them into the Seahub project code to complete the translation.

Thank you for your support of our translation work 👍

**Comment by Michael18811380328** [comment]
We have regularly downloaded translation files from Transifex and updated them into the Seahub project code to complete the translation. This is the relevant pull requrest, https://github.com/haiwen/seahub/pull/7143 ,The Slovenian language translation you submitted has been updated. Thank you for your support of our translation work 👍 
截屏2024-12-05 11 41 44

**Pull request closed without merging**
