### PR TITLE
Correction of the French language (spelling, conjugation ...)

### PR DESCRIPTION
**Pull request by FleuryK**
Hello.

I have been for some time your project and I find it very well compared to OwnCloud.

I made some corrections (notably orthographic, conjugation and syntax) on the French language.

Hopefully these corrections will be in the upcoming update.

Cordially.

### CODE REVIEW

**Comment by xiez** [comment]
Hi @FleuryK , thanks for your work! Could u plz submit your translations on Transifex  according to https://github.com/haiwen/seafile/wiki/Seahub-Translation#submit-translation ?

Many thanks!

**Comment by shoeper** [comment]
Have these translations been uploaded to transifex?

**Comment by FleuryK** [comment]
Hello @shoeper,

Yes, I have uploaded my translations to transifex but it doesn't effect.

**Comment by shoeper** [comment]
> Yes, I have uploaded my translations to transifex
Great!

> but it doesn't effect.
I'm no maintainer / dev, but they'll be pulled before the next release I think.

**Pull request closed without merging**
