### PR TITLE
New token time

### PR DESCRIPTION
**Pull request by guopengda**

### CODE REVIEW

**Comment by omkarnathsingh** [comment]
What is benefit of this feature?

**Comment by shoeper** [comment]
@omkarnathsingh so far tokens never expire. When enabling this api token will expire after a given time.

**Comment by omkarnathsingh** [comment]
Ah, nice. Let me try it and add to my seafile. Thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by shoeper** [comment]
Main question I'd have it this also effects the clients. There one usually doesn't want to get logged out.

**Comment by omkarnathsingh** [comment]
@shoeper Can we have better have it as a setting for SYstem admin to either enable or not. I feel if its added, it will expire token for android/windows app also making it to login again and again.

**Pull request closed without merging**
