### PR TITLE
add role permission to hide send mail button on share/uplink link dialog

### PR DESCRIPTION
**Pull request by TMHBOFH**
i hope the implementation is correct and you would be merged this PR

### CODE REVIEW

**Comment by xiez** [comment]
@TMHBOFH Thanks for you working!

Shall we use `can_send_share_link_mail` instead of `can_send_share_upload_link_mail` since it's for both download link and upload link ?

BTW, please merge multiple commits into one commit.

**Comment by TMHBOFH** [comment]
@xiez 
i have renamed into can_send_share_link_mail and sorry for the multiple commits.
In the future I will do only one commit.

**Comment by TMHBOFH** [comment]
@xiez it would be nice if you could check this and [this](https://github.com/haiwen/seahub/pull/1687) PR

Best Regards

**Comment by xiez** [comment]
Hi @TMHBOFH , merged & thank you!

BTW, sorry for the late response, just back from vacation.

**Pull request merged**
